# Vault ServiceAccount configuration
serviceAccount:
  name: vault-auth
  namespace: argocd-go-example

# LoadBalancer configuration
loadBalancer:
  enabled: true
  externalTrafficPolicy: Local
  targetPort: 8200
  ports:
    http: 80
    https: 443

# Vault Ingress for Traefik
ingress:
  enabled: true
  className: traefik
  host: vault.techbit.su
  service:
    name: vault-ui
    port: 8200

ingressRoute:
  enabled: true
  entryPoints:
    web: web
    websecure: websecure
  tls:
    secretName: vault-tls-selfsigned
    options:
      name: vault-tlsoption
      namespace: vault

tlsOption:
  enabled: true
  name: vault-tlsoption
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
