---
# LoadBalancer сервис для Traefik HTTPS на порту 443
apiVersion: v1
kind: Service
metadata:
  name: traefik-https-lb
  namespace: traefik-system
  labels:
    app: traefik
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: websecure
      port: 443
      targetPort: websecure
      protocol: TCP
  selector:
    app: traefik
---
# LoadBalancer сервис для Traefik HTTP на порту 80
apiVersion: v1
kind: Service
metadata:
  name: traefik-http-lb
  namespace: traefik-system
  labels:
    app: traefik
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: traefik
