---
# TLSOption для Vault - разрешаем TLS 1.2 и 1.3
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: vault-tlsoption
  namespace: vault
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
---
# IngressRoute для HTTPS
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingressroute
  namespace: vault
  labels:
    app: vault
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.techbit.su`)
      kind: Rule
      services:
        - name: vault-ui
          port: 8200
  tls:
    secretName: vault-tls-selfsigned
    options:
      name: vault-tlsoption
---
# IngressRoute для HTTP
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-http
  namespace: vault
  labels:
    app: vault
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.techbit.su`)
      kind: Rule
      services:
        - name: vault-ui
          port: 8200
