apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-ingress

resources:
  - manifests.yaml
  - ingress-resources.yaml

commonLabels:
  app.kubernetes.io/name: envoy-ingress
