apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-tls
  namespace: default
spec:
  secretName: envoy-gateway-tls-secret
  duration: 8760h # 1 год
  renewBefore: 720h # 30 дней до истечения
  commonName: "techbit.su"
  dnsNames:
    - "techbit.su"
    - "*.techbit.su"
    - argocd.techbit.su
    - grafana.techbit.su
    - app.techbit.su
    - longhorn.techbit.su
    - vault.techbit.su
  ipAddresses:
    - 192.168.0.200
    - 192.168.0.101
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
