# Self-signed ClusterIssuer для локальных сертификатов
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# TLS сертификат для Go приложения (Let's Encrypt)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-go-example-tls
  namespace: argocd-go-example
spec:
  secretName: argocd-go-example-tls
  duration: 2160h  # 90 дней
  renewBefore: 360h  # 15 дней до истечения
  subject:
    organizations:
      - argocd-go-example
  commonName: app.techbit.su
  dnsNames:
    - app.techbit.su
  issuerRef:
    name: letsencrypt-prod-envoy
    kind: ClusterIssuer
---
# TLS сертификат для Vault (Let's Encrypt)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - vault
  commonName: vault.techbit.su
  dnsNames:
    - vault.techbit.su
  issuerRef:
    name: letsencrypt-prod-envoy
    kind: ClusterIssuer
