# Vault ServiceAccount для аутентификации
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "vault-auth" }}
  namespace: {{ .Values.serviceAccount.namespace | default "argocd-go-example" }}
  annotations:
    description: "ServiceAccount для аутентентификации в Vault"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default "vault-auth" }}
    namespace: {{ .Values.serviceAccount.namespace | default "argocd-go-example" }}
