apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pritunl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
    path: deploy/apps/pritunl
  destination:
    server: https://kubernetes.default.svc
    namespace: pritunl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/storageClassName
        - /spec/volumeName
  health:
    resourceHealthChecks:
      - group: apps
        kind: Deployment
        check:
          lua: |
            hs = {}
            if obj.status ~= nil then
              if obj.status.conditions ~= nil then
                for i, condition in ipairs(obj.status.conditions) do
                  if condition.type == "Available" then
                    if condition.status == "True" then
                      hs.status = "Healthy"
                      return hs
                    end
                  end
                end
              end
            end
            hs.status = "Progressing"
            return hs
      - group: apps
        kind: StatefulSet
        check:
          lua: |
            hs = {}
            if obj.status ~= nil then
              if obj.status.conditions ~= nil then
                for i, condition in ipairs(obj.status.conditions) do
                  if condition.type == "Ready" then
                    if condition.status == "True" then
                      hs.status = "Healthy"
                      return hs
                    end
                  end
                end
              end
            end
            hs.status = "Progressing"
            return hs
      - group: ""
        kind: Service
        check:
          lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      - group: ""
        kind: PersistentVolumeClaim
        check:
          lua: |
            hs = {}
            if obj.status ~= nil then
              if obj.status.phase == "Bound" then
                hs.status = "Healthy"
                return hs
              end
            end
            hs.status = "Progressing"
            return hs
