apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/infrastructure/envoy-gateway
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
