apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts/
    chart: grafana
    targetRevision: 8.8.2
    helm:
      releaseName: grafana
      values: |
        adminPassword: admin
        service:
          type: ClusterIP
          port: 80
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: VictoriaMetrics
                type: prometheus
                url: http://vmselect-victoriametrics.victoriametrics.svc:8481/select/0/prometheus/
                access: proxy
                isDefault: true
                editable: true
        persistence:
          enabled: true
          size: 5Gi
          storageClassName: local-path
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
