apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts/
    chart: grafana
    targetRevision: 8.8.2
    helm:
      releaseName: grafana
      values: |
        adminPassword: admin
        service:
          type: ClusterIP
          port: 80
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: VictoriaMetrics
                type: prometheus
                url: http://vmselect-victoriametrics.victoriametrics.svc:8481/select/0/prometheus/
                access: proxy
                isDefault: true
                editable: true
        persistence:
          enabled: true
          size: 5Gi
          storageClassName: local-path
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        sidecar:
          dashboards:
            enabled: true
            searchNamespace: ALL
            provider:
              name: kubernetes-dashboards
              folder: Kubernetes
        dashboards:
          kubernetes:
            kubernetes-cluster:
              gnetId: 6417
              revision: 1
              datasource: VictoriaMetrics
            kubernetes-nodes:
              gnetId: 14205
              revision: 1
              datasource: VictoriaMetrics
            kubernetes-pods:
              gnetId: 6336
              revision: 1
              datasource: VictoriaMetrics
            kubernetes-namespaces:
              gnetId: 14206
              revision: 1
              datasource: VictoriaMetrics
            kubernetes-statefulset:
              gnetId: 14207
              revision: 1
              datasource: VictoriaMetrics
            kubernetes-deployment:
              gnetId: 14208
              revision: 1
              datasource: VictoriaMetrics
            kubernetes-daemonset:
              gnetId: 14209
              revision: 1
              datasource: VictoriaMetrics
            victoria-metrics:
              gnetId: 10225
              revision: 1
              datasource: VictoriaMetrics
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
