apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-repos
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repo-creds
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  type: helm
  url: https://helm.releases.hashicorp.com
  name: hashicorp
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-repos-victoriametrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repo-creds
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  type: helm
  url: https://victoriametrics.github.io/helm-charts/
  name: victoriametrics
