apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-go-example

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: argocd-go-example

images:
  - name: argocd-go-example
    newName: argocd-go-example
    newTag: latest
