apiVersion: v1
kind: Secret
metadata:
  name: argocd-go-example-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/derunov/argocd-go-example.git
  username: <GITHUB_USERNAME>
  password: <GITHUB_TOKEN>
