apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-operator
    targetRevision: 0.29.0
    helm:
      values: |
        operator:
          enableCRD: true
  destination:
    server: https://kubernetes.default.svc
    namespace: victoriametrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
    path: deploy/victoriametrics
  destination:
    server: https://kubernetes.default.svc
    namespace: victoriametrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
