apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-operator
    targetRevision: 0.35.0
    helm:
      releaseName: victoriametrics
      values: |
        operator:
          enableCRD: true
        crds:
          enabled: true
        webhook:
          enabled: false
        admissionWebhooks:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: victoriametrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: victoriametrics-victoria-metrics-operator-admission
      - group: ''
        kind: Secret
        name: victoriametrics-victoria-metrics-operator-validation
        namespace: victoriametrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: victoriametrics
  namespace: victoriametrics
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: cluster
spec:
  retentionPeriod: "1"
  replicationFactor: 1

  vminsert:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  vmselect:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  vmstorage:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 5Gi
