gitlabUrl: http://gitlab.techbit.su
runnerToken: "glrt-ZORzIVOYhn7w1RJhodiEam86MQp0OjEKdToxCw.01.120g8j536"  # Runner Authentication Token (GitLab 16+)
runners:
  config: |
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-ci"
        image = "ubuntu:22.04"
        privileged = false
  concurrent: 10
  checkInterval: 10
