apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pritunl

resources:
  - namespace.yaml
  - mongodb-statefulset.yaml
  - mongodb-service.yaml
  - pritunl-configmap.yaml
  - pritunl-deployment.yaml
  - pritunl-services.yaml

commonLabels:
  app: pritunl
