namespace: gitlab
ingress:
  enabled: true
  className: traefik
  host: gitlab.techbit.su
certificate:
  enabled: true
  secretName: gitlab-tls
initialPassword:
  enabled: true
  secretName: gitlab-initial-password
