# Grafana Ingress for Traefik
grafana:
  ingress:
    enabled: true
    className: traefik
    host: grafana.techbit.su
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    service:
      name: vm-stack-2-grafana
      port: 80
