apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritunl
  namespace: pritunl
  labels:
    app: pritunl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pritunl
  template:
    metadata:
      labels:
        app: pritunl
    spec:
      containers:
      - name: pritunl
        image: docker.io/jippi/pritunl:1.32.4567.52
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 1194
          name: openvpn
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /etc/pritunl/pritunl.conf
          subPath: pritunl.conf
        - name: data
          mountPath: /var/lib/pritunl
        env:
        - name: TZ
          value: "Europe/Moscow"
        - name: PRITUNL_MONGODB_URI
          value: "mongodb://mongodb:27017/pritunl"
        - name: PRITUNL_REVERSE_PROXY
          value: "true"
        - name: PRITUNL_APP_URL
          value: "http://pritunl.pritunl.svc.cluster.local"
        - name: PRITUNL_HTTP_PORT
          value: "80"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
      volumes:
      - name: config
        configMap:
          name: pritunl-config
      - name: data
        emptyDir: {}
