apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pritunl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  source:
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
    path: deploy/applications/pritunl
  destination:
    server: https://kubernetes.default.svc
    namespace: pritunl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/storageClassName
        - /spec/volumeName
