{{- if .Values.ingressRoute.enabled }}
---
# TLSOption для Vault
{{- if .Values.tlsOption.enabled }}
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: {{ .Values.tlsOption.name }}
  namespace: {{ .Values.tlsOption.options.namespace | default "vault" }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  minVersion: {{ .Values.tlsOption.minVersion }}
  maxVersion: {{ .Values.tlsOption.maxVersion }}
  cipherSuites:
    {{- toYaml .Values.tlsOption.cipherSuites | nindent 4 }}
{{- end }}
---
# IngressRoute для HTTPS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingressroute
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoints.websecure }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.ingress.service.name }}
          port: {{ .Values.ingress.service.port }}
  tls:
    secretName: {{ .Values.ingressRoute.tls.secretName }}
    options:
      name: {{ .Values.ingressRoute.tls.options.name }}
      namespace: {{ .Values.ingressRoute.tls.options.namespace }}
---
# IngressRoute для HTTP
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-http
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoints.web }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.ingress.service.name }}
          port: {{ .Values.ingress.service.port }}
{{- end }}
