apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
    path: deploy/infrastructure/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: victoriametrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  health:
    resourceHealthChecks:
      - group: networking.k8s.io
        kind: Ingress
        check:
          lua: |
            hs = {}
            hs.status = "Healthy"
            hs.message = "Ingress is healthy"
            return hs
      - group: ""
        kind: ConfigMap
        check:
          lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
