apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
    path: deploy/infrastructure/grafana
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: traefik.io
      kind: IngressRoute
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/uid
