apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.8.2
    helm:
      releaseName: grafana
      values: |
        adminPassword: admin
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: false
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - access: proxy
              isDefault: true
              name: VictoriaMetrics
              type: prometheus
              url: http://vmsingle-victoriametrics.victoriametrics.svc:8429
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
