apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sterks/argocd-go-example.git
    targetRevision: HEAD
    path: deploy/infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/spec/nodeSelector
  health:
    resourceHealthChecks:
      - group: ""
        kind: Service
        check:
          lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      - group: apps
        kind: Deployment
        check:
          lua: |
            hs = {}
            if obj.status ~= nil then
              if obj.status.conditions ~= nil then
                for i, condition in ipairs(obj.status.conditions) do
                  if condition.type == "Available" then
                    if condition.status == "True" then
                      hs.status = "Healthy"
                      return hs
                    end
                  end
                end
              end
            end
            hs.status = "Progressing"
            return hs
