---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: my-postgres-cluster
  namespace: postgresql
  labels:
    app.kubernetes.io/instance: my-postgres-cluster
spec:
  teamId: "myteam"
  numberOfInstances: 1
  users:
    appuser:
    - superuser
    - createdb
  databases:
    appdb: appuser
  postgresql:
    version: "16"
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  volume:
    size: 100Gi
    storageClass: longhorn
  patroni:
    sync_mode: false
    synchronous_node_count: 1
    failsafe_mode: false
  usersWithSecretRotation: []
  tls:
    secretName: ""
  additionalVolumes: []
